# Generated by Django 6.0.5 on 2026-05-20 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email_institucional', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato'), ('TERMO_COMPROMISSO', 'Termo de Compromisso'), ('RELATORIO_PARCIAL', 'Relatório Parcial'), ('RELATORIO_FINAL', 'Relatório Final'), ('APOLICE_SEGURO', 'Apólice de Seguro'), ('OUTRO', 'Outro')], max_length=30)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('VALIDADO', 'Validado'), ('COM_PENDENCIA', 'Com Pendência'), ('REJEITADO', 'Rejeitado'), ('ASSINADO', 'Assinado')], default='ENVIADO', max_length=30)),
                ('caminho_arquivo', models.FileField(upload_to='documentos_estagio/')),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('responsavel_legal', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato'), ('TERMO_COMPROMISSO', 'Termo de Compromisso'), ('RELATORIO_PARCIAL', 'Relatório Parcial'), ('RELATORIO_FINAL', 'Relatório Final'), ('APOLICE_SEGURO', 'Apólice de Seguro'), ('OUTRO', 'Outro')], max_length=30)),
                ('versao', models.CharField(max_length=10)),
                ('arquivo_modelo', models.FileField(upload_to='modelos/')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('EM_PREENCHIMENTO', 'Em Preenchimento'), ('SUBMETIDA', 'Submetida'), ('EM_VALIDACAO', 'Em Validação'), ('COM_PENDENCIAS', 'Com Pendências'), ('EM_ANALISE_EXCECAO', 'Em Análise de Exceção'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada')], default='EM_PREENCHIMENTO', max_length=30)),
                ('score_conformidade', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
                ('setor', models.CharField(max_length=100)),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.IntegerField()),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.usuario')),
                ('area_atuacao', models.CharField(max_length=100)),
            ],
            bases=('core.usuario',),
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('nome_assinante', models.CharField(max_length=255)),
                ('cargo_assinante', models.CharField(max_length=100)),
                ('hash_validacao', models.CharField(max_length=255)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.usuario')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='core.documento')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresaparceira')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='modelo_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelodocumento'),
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DADO_AUSENTE', 'Dado Ausente'), ('ASSINATURA_FALTANTE', 'Assinatura Faltante'), ('DOCUMENTO_INVALIDO', 'Documento Inválido'), ('INCONSISTENCIA_LEGAL', 'Inconsistência Legal'), ('INCONSISTENCIA_INSTITUCIONAL', 'Inconsistência Institucional')], max_length=50)),
                ('descricao', models.TextField()),
                ('obrigatoria', models.BooleanField(default=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='core.solicitacaoestagio')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STATUS_ALTERADO', 'Status Alterado'), ('PENDENCIA_IDENTIFICADA', 'Pendência Identificada'), ('PRAZO_PROXIMO', 'Prazo Próximo'), ('DOCUMENTO_ASSINADO', 'Documento Assinado')], max_length=50)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.usuario')),
                ('solicitacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.solicitacaoestagio')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.solicitacaoestagio'),
        ),
        migrations.CreateModel(
            name='ValidacaoAutomatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_processamento', models.DateTimeField(auto_now_add=True)),
                ('tempo_processamento_seg', models.IntegerField()),
                ('regras_aplicadas', models.TextField()),
                ('resultado', models.TextField()),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.solicitacaoestagio')),
            ],
        ),
        migrations.CreateModel(
            name='AnaliseExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('decisao', models.CharField(blank=True, choices=[('APROVAR_EXCECAO', 'Aprovar Exceção'), ('SOLICITAR_AJUSTE', 'Solicitar Ajuste'), ('REPROVAR', 'Reprovar')], max_length=30, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('data_analise', models.DateField(blank=True, null=True)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.solicitacaoestagio')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.coordenador')),
            ],
        ),
        migrations.AddField(
            model_name='solicitacaoestagio',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='core.estudante'),
        ),
        migrations.CreateModel(
            name='RelatorioEstagio',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.documento')),
                ('titulo', models.CharField(max_length=255)),
                ('periodo_referencia', models.CharField(max_length=50)),
                ('parecer', models.TextField(blank=True, null=True)),
                ('conceito', models.CharField(blank=True, max_length=50, null=True)),
                ('professor_avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor')),
            ],
            bases=('core.documento',),
        ),
    ]
