# Generated by Django 6.0.6 on 2026-06-11 23:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('tipo', models.CharField(choices=[('CONTRATO', 'Contrato'), ('TERMO_COMPROMISSO', 'Termo de Compromisso'), ('RELATORIO_PARCIAL', 'Relatório Parcial'), ('RELATORIO_FINAL', 'Relatório Final'), ('APOLICE_SEGURO', 'Apólice de Seguro'), ('OUTRO', 'Outro')], max_length=30)),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('VALIDADO', 'Validado'), ('COM_PENDENCIA', 'Com Pendência'), ('REJEITADO', 'Rejeitado'), ('ASSINADO', 'Assinado')], default='ENVIADO', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('responsavel_legal', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('versao', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('tipo', models.CharField(choices=[('ESTUDANTE', 'Estudante'), ('PROFESSOR', 'Professor'), ('COORDENADOR', 'Coordenador')], max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('matricula', models.CharField(blank=True, max_length=30, null=True)),
                ('curso', models.CharField(blank=True, max_length=100, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('area_atuacao', models.CharField(blank=True, max_length=100, null=True)),
                ('setor', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='estagios_usuario_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='estagios_usuario_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_assinatura', models.CharField(max_length=255)),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='estagios.documento')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estagios.modelodocumento'),
        ),
        migrations.CreateModel(
            name='SolicitacaoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('EM_PREENCHIMENTO', 'Em preenchimento'), ('SUBMETIDA', 'Submetida'), ('EM_VALIDACAO', 'Em validação'), ('COM_PENDENCIAS', 'Com pendências'), ('EM_ANALISE_EXCECAO', 'Em análise de exceção'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada')], default='EM_PREENCHIMENTO', max_length=30)),
                ('score_conformidade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='estagios.empresaparceira')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_estudante', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_professor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_entrega', models.DateField()),
                ('aprovado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='estagios.solicitacaoestagio')),
            ],
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DADO_AUSENTE', 'Dado Ausente'), ('ASSINATURA_FALTANTE', 'Assinatura Faltante'), ('DOCUMENTO_INVALIDO', 'Documento Inválido'), ('INCONSISTENCIA_LEGAL', 'Inconsistência Legal'), ('INCONSISTENCIA_INSTITUCIONAL', 'Inconsistência Institucional')], max_length=50)),
                ('descricao', models.TextField()),
                ('resolvida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='estagios.solicitacaoestagio')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('STATUS_ALTERADO', 'Status Alterado'), ('PENDENCIA_IDENTIFICADA', 'Pendência Identificada'), ('PRAZO_PROXIMO', 'Prazo Próximo'), ('DOCUMENTO_ASSINADO', 'Documento Assinado')], max_length=50)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_usuario', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='estagios.solicitacaoestagio')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estagios.solicitacaoestagio'),
        ),
        migrations.CreateModel(
            name='AnaliseExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.TextField()),
                ('decisao', models.CharField(choices=[('APROVAR_EXCECAO', 'Aprovar Exceção'), ('SOLICITAR_AJUSTE', 'Solicitar Ajuste'), ('REPROVAR', 'Reprovar')], max_length=30)),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise_excecao', to='estagios.solicitacaoestagio')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('cargo', models.CharField(max_length=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisores', to='estagios.empresaparceira')),
            ],
        ),
        migrations.AddField(
            model_name='solicitacaoestagio',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estagios.supervisorempresa'),
        ),
    ]
